/**
 * 阵列位移计采集器命令列表
 */
export enum TxtCommands {
  GET_MODE = 'GET_MODE',
  GET_DATA = 'GET_DATA',
  GET_MDATA = 'GET_MDATA',
  GET_NODES = 'GET_NODES',
  GET_TWIST = 'GET_TWIST',
  GET_TIME = 'GET_TIME',
  GET_INTERVAL = 'GET_INTERVAL',
  GET_VERSION = 'GET_VERSION',
  GET_DEVICES = 'GET_DEVICES',
  GET_UPLOAD_MODEL = 'GET_UPLOAD_MODEL',
  RESET = 'RESET',
  SAVE = 'SAVE',
  UPDATE_TIME = 'UPDATE_TIME',
  SET_MODE = 'SET_MODE',
  SET_INTERVAL = 'SET_INTERVAL',
  SET_TWIST = 'SET_TWIST',
  GET_UPLOAD_MODE = 'GET_UPLOAD_MODE',
  SET_UPLOAD_MODE = 'SET_UPLOAD_MODE',
  INACTIVE_UPLOAD = 'INACTIVE_UPLOAD',
  ACTIVE_MDATA_UPLOAD = 'ACTIVE_MDATA_UPLOAD',
  ACTIVE_TMDATA_UPLOAD = 'ACTIVE_TMDATA_UPLOAD',
  ACTIVE_DATA_UPLOAD = 'ACTIVE_DATA_UPLOAD',
  OK = 'OK',
  GET_GLIMIT = 'GET_GLIMIT',
  SET_GLIMIT = 'SET_GLIMIT',
  GET_HISTORY = 'GET_HISTORY',
  UPDATE_NODES = 'UPDATE_NODES',
}

/**
 * 数采命令列表
 */
export enum HdaCommands {
  GET_SY_DATA = 'GET_SY_DATA',
  GET_SY_HISTORY_DATA = 'GET_SY_HISTORY_DATA',
  GET_CSQ = 'GET_CSQ',
  GET_DEVICE_TIME = 'GET_DEVICE_TIME',
  GET_SDMPRO_G = 'GET_SDMPRO_G',
  GET_SDMPRO_ANGLE = 'GET_SDMPRO_ANGLE',
  GET_WAKE_UP_INTERVAL = 'GET_WAKE_UP_INTERVAL',
  SET_DEVICE_TIME = 'SET_DEVICE_TIME',
  SET_WAKE_UP = 'SET_WAKE_UP',
  SET_SLEEP = 'SET_SLEEP',
  SET_AWAKE = 'SET_AWAKE',
  SET_FAST_SLEEP = 'SET_FAST_SLEEP',
  SET_RESET = 'SET_RESET',
  SET_INIT = 'SET_INIT',
  SET_ONLINE = 'SET_ONLINE',
  SET_SDMPRO_SWITCH = 'SET_SDMPRO_SWITCH',
  SET_VIBR_FREQ = 'SET_VIBR_FREQ',
  SET_VIBR_DETECT_FREQ = 'SET_VIBR_DETECT_FREQ',
  SET_VIBR_DETECT_SENS = 'SET_VIBR_DETECT_SENS',
  SET_SDMPRO_ALARM_TIME = 'SET_SDMPRO_ALARM_TIME',
  SET_ANGLE_INTERVAL = 'SET_ANGLE_INTERVAL',
  SET_HDA = 'SET_HDA',

  // GDM
  GET_GDM_INFO = 'GET_GDM_INFO',
  GET_GDM_SERVER = 'GET_GDM_SERVER',
  GET_GDM_APN = 'GET_GDM_APN',
  GET_GDM_IMU = 'GET_GDM_IMU',
  GET_GDM_NETWORK_STATUS = 'GET_GDM_NETWORK_STATUS',
  GET_GDM_STATIC_LIST = 'GET_GDM_STATIC_LIST',
  GET_GDM_STATIC = 'GET_GDM_STATIC',
  GET_GDM_STATUS = 'GET_GDM_STATUS',
  GET_GDM_SELF_CHECK = 'GET_GDM_SELF_CHECK',
  GET_GDM_DATA_CONFIG = 'GET_GDM_DATA_CONFIG',
  GET_GDM_MODE = 'GET_GDM_MODE',
  SET_GDM_SERVER = 'SET_GDM_SERVER', // 设置服务器参数
  SET_GDM_APN = 'SET_GDM_APN', // 设置网络连接参数
  SET_GDM_IMU = 'SET_GDM_IMU', // 设置IMU输出频率
  REG_DEV = 'REG_DEV',
  SET_GDM_DATA_CONFIG = 'SET_GDM_DATA_CONFIG',
  SET_GDM_MODE = 'SET_GDM_MODE',
}
